---
- hosts: all
  sudo: yes
  vars:
    cluster_name: Test Cluster
    vagrant_ip: 192.168.10.10
    seeds: 192.168.10.10

  tasks:
  - name: install htop
    apt: name=htop state=present

  roles:
    - cassandra
    - opscenter
    - spark


